version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
max_jobs: 2
image: Visual Studio 2017
configuration: Release
platform: x64
clone_folder: C:\projects\myproject
install:
- cmd: git submodule update --init --recursive
- ps: |
    Remove-Item C:\OpenSSL-Win32 -Force -Recurse
    Remove-Item C:\OpenSSL-Win64 -Force -Recurse
    Move-Item C:\OpenSSL-v111-Win64 C:\OpenSSL-Win64 -Force
before_build:
- cmake -DBoost_COMPILER="-vc141" -DBOOST_ROOT="C:/Libraries/boost_1_67_0" -DBOOST_LIBRARYDIR="C:/Libraries/boost_1_67_0/lib64-msvc-14.1" -G "Visual Studio 15 2017 Win64" -DIPHLPAPI_LIBRARY="C:/Program Files (x86)/Windows Kits/10/Lib/10.0.14393.0/um/x64/iphlpapi.lib" -DWINSOCK2_LIBRARY="C:/Program Files (x86)/Windows Kits/10/Lib/10.0.14393.0/um/x64/WS2_32.lib"
build_script:
- cmake --build "%APPVEYOR_BUILD_FOLDER%" --config "%CONFIGURATION%" --target rai_node -- /maxcpucount /verbosity:minimal
after_build:
- ps: |
    $cscFile = Join-Path -Path "$Env:TMP" -ChildPath csc.p12
    [IO.File]::WriteAllBytes($cscFile, [Convert]::FromBase64String($Env:CSC_LINK))
    Set-AppveyorBuildVariable -Name 'CSC_FILE' -Value $cscFile
- cmd: |
    "C:\Program Files (x86)\Windows Kits\10\App Certification Kit\signtool.exe" sign /a /f "%CSC_FILE%" /p "%CSC_KEY_PASSWORD%" /tr http://timestamp.digicert.com /td sha256 /fd sha256 "%APPVEYOR_BUILD_FOLDER%/Release/rai_node.exe"
- ps: Remove-Item -Path $Env:CSC_FILE
- cmd: 7z a -tzip -mx=9 node-win32.zip "%APPVEYOR_BUILD_FOLDER%/Release/rai_node.exe"
artifacts:
- path: node-win32.zip
  name: node-win32
